image: alpine

stages:
  - build
  - test
  - mutation-test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache: &cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

.base: &base
  image: node:12
  tags:
    - dind
  except:
    - master
    - tags

Build & Lint:
  stage: build
  <<: *base
  script:
    - npm ci
    - npm run build
    - npm run lint

Unit & E2E Tests:
  stage: test
  <<: *base
  image: cypress/base:10
  cache:
    <<: *cache
    policy: pull
  script:
    - npm test
    - npm run test:e2e:ci

Test mutations:
  image: node:12
  tags:
    - dind
  stage: mutation-test
  cache:
    <<: *cache
    policy: pull
  when: manual
  script:
    - npm run test:mutation
  artifacts:
    paths:
      - ./reports/mutation/html
    expire_in: 7 days
    name: ${CI_COMMIT_REF_SLUG}
