import React, { FC, Fragment } from 'react'
import Counter from '../components/counter/Counter'

export const Home: FC = () => {
  return (
    <Fragment>
      <h1>React Project Skeleton, Default Version</h1>
      <p>
        App generated by using <strong>create-react-app --template pi</strong>
      </p>
      <Counter />
    </Fragment>
  )
}
